// <auto-generated />
using System;
using ERP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERP.Migrations
{
    [DbContext(typeof(ERPContext))]
    [Migration("20260202044702_updatereplay")]
    partial class updatereplay
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ERP.Models.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AttachmentPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeletedByReceiver")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeletedBySender")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelivered")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReceiverId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ReplyToMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReplyToMessageId")
                        .HasColumnType("int");

                    b.Property<string>("ReplyToSenderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("ERP.Models.CoInqueryItem", b =>
                {
                    b.Property<int>("CoInqueryItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoInqueryItemID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTemp")
                        .HasColumnType("bit");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double?>("Price1")
                        .HasColumnType("float");

                    b.Property<double?>("Price2")
                        .HasColumnType("float");

                    b.Property<double?>("Price3")
                        .HasColumnType("float");

                    b.Property<double?>("Price4")
                        .HasColumnType("float");

                    b.Property<double?>("Price5")
                        .HasColumnType("float");

                    b.Property<double?>("Price6")
                        .HasColumnType("float");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.HasKey("CoInqueryItemID");

                    b.ToTable("CoInqueryItems");
                });

            modelBuilder.Entity("ERP.Models.CoTenderItem", b =>
                {
                    b.Property<int>("CoTenderItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoTenderItemID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTemp")
                        .HasColumnType("bit");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double?>("Price1")
                        .HasColumnType("float");

                    b.Property<double?>("Price2")
                        .HasColumnType("float");

                    b.Property<double?>("Price3")
                        .HasColumnType("float");

                    b.Property<double?>("Price4")
                        .HasColumnType("float");

                    b.Property<double?>("Price5")
                        .HasColumnType("float");

                    b.Property<double?>("Price6")
                        .HasColumnType("float");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<double?>("Score")
                        .HasColumnType("float");

                    b.Property<double?>("Score1")
                        .HasColumnType("float");

                    b.Property<double?>("Score2")
                        .HasColumnType("float");

                    b.Property<double?>("Score3")
                        .HasColumnType("float");

                    b.Property<double?>("Score4")
                        .HasColumnType("float");

                    b.Property<double?>("Score5")
                        .HasColumnType("float");

                    b.Property<double?>("Score6")
                        .HasColumnType("float");

                    b.HasKey("CoTenderItemID");

                    b.ToTable("CoTenderItems");
                });

            modelBuilder.Entity("ERP.Models.CompanyInquery", b =>
                {
                    b.Property<int>("CompanyInqueryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyInqueryID"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("FeeCost")
                        .HasColumnType("float");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InqueryResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NeedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NeedNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.Property<string>("Winner")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyInqueryID");

                    b.ToTable("CompanyInquerys");
                });

            modelBuilder.Entity("ERP.Models.CompanyTender", b =>
                {
                    b.Property<int>("CompanyTenderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyTenderID"));

                    b.Property<string>("AlefDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AllPocketDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("FeeCost")
                        .HasColumnType("float");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenderResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.Property<string>("Winner")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyTenderID");

                    b.ToTable("CompanyTenders");
                });

            modelBuilder.Entity("ERP.Models.FileDB", b =>
                {
                    b.Property<int>("FileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FileID"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTemp")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FileID");

                    b.ToTable("FileDBs");
                });

            modelBuilder.Entity("ERP.Models.GoodsConsigned", b =>
                {
                    b.Property<int>("GoodsConsignedID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GoodsConsignedID"));

                    b.Property<string>("ConsignedItem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Darkhast_persiandate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Khodro_Enteringtheguard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Khoruj_persiandate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MahalDaryaft")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_Darkhastkonnande")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone_Enteringtheguard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S_persiandate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S_persiandate_Enteringtheguard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaateKhoruj_Enteringtheguard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaateVorud_Enteringtheguard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shomare_Serial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shomare_Serial_Enteringtheguard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TahvilDahande_Enteringtheguard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TayidMali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TayidMasool")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TayidModirAmel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TayidTadarokat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tayid_Sanaye")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeKhoruj_persiandate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tozihat_Anbar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tozihat_Mali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tozihat_Masool")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tozihat_ModirAmel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tozihat_Negahbani")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tozihat_Net")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tozihat_Tadarokat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tozihat_TayidSanaye")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeSending")
                        .HasColumnType("int");

                    b.HasKey("GoodsConsignedID");

                    b.ToTable("GoodsConsigneds");
                });

            modelBuilder.Entity("ERP.Models.GoodsConsignedItemGuard", b =>
                {
                    b.Property<int>("GoodsConsignedItemGuardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GoodsConsignedItemGuardID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GoodsConsignedID")
                        .HasColumnType("int");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SharhKala")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tedad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vahed")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GoodsConsignedItemGuardID");

                    b.HasIndex("GoodsConsignedID");

                    b.ToTable("GoodsConsignedItemGuards");
                });

            modelBuilder.Entity("ERP.Models.GoodsDeparture", b =>
                {
                    b.Property<int>("GoodsDepartureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GoodsDepartureID"));

                    b.Property<string>("Code_TahvilGirandeh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date_persiandate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsBazrasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nam_TahvilGirandeh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_Anbar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Noe_Hamel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S_persiandate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shomareh_Anabr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shomareh_havale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Taeed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tozihat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tozihat_Entezamat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tozihat_Mali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleExit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GoodsDepartureID");

                    b.ToTable("GoodsDepartures");
                });

            modelBuilder.Entity("ERP.Models.GoodsEntry", b =>
                {
                    b.Property<int>("GoodsEntryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GoodsEntryID"));

                    b.Property<string>("BarrasiQC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsApprovedByEng")
                        .HasColumnType("bit");

                    b.Property<string>("Khodro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoeKala")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S_persiandate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S_persiandatetoQC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaateKhoruj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaateVorud")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialAnbar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShomareBargasht")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShomarePPAP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shomare_Serial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shomarekala")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TahvilDahande")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TozihatAnbar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TozihatEng")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TozihatKeyfiat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TozihatOther")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TozihatSanaye")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TozihatTolid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("isTahvil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("isTayedTolid")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GoodsEntryID");

                    b.ToTable("GoodsEntries");
                });

            modelBuilder.Entity("ERP.Models.GoodsEntryItem", b =>
                {
                    b.Property<int>("GoodsEntryItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GoodsEntryItemID"));

                    b.Property<string>("Azmoon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GoodsEntryID")
                        .HasColumnType("int");

                    b.Property<string>("Guid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameKala")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameTaminkonandeh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Natigeh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parameter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShonarehResid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tedad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TedadNemoneh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tozihat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vahed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("iSENG")
                        .HasColumnType("bit");

                    b.HasKey("GoodsEntryItemID");

                    b.ToTable("GoodsEntryItems");
                });

            modelBuilder.Entity("ERP.Models.GoodsEntryItemGuard", b =>
                {
                    b.Property<int>("GoodsEntryItemGuardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GoodsEntryItemGuardID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GoodsEntryID")
                        .HasColumnType("int");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SharhKala")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tedad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vahed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GoodsEntryItemGuardID");

                    b.ToTable("GoodsEntryItemGuards");
                });

            modelBuilder.Entity("ERP.Models.Group", b =>
                {
                    b.Property<int>("GroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GroupID");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("ERP.Models.GuaranteeLetter", b =>
                {
                    b.Property<int>("GuaranteeLetterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GuaranteeLetterId"));

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DistributionCompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpirationDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpirationDateGregorian")
                        .HasColumnType("datetime2");

                    b.Property<string>("FollowUpResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuaranteeNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuaranteeStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuaranteeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssueDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IssueDateGregorian")
                        .HasColumnType("datetime2");

                    b.Property<string>("OverdueProgressPercentage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegDateGregorian")
                        .HasColumnType("datetime2");

                    b.HasKey("GuaranteeLetterId");

                    b.ToTable("GuaranteeLetters");
                });

            modelBuilder.Entity("ERP.Models.GuestEntry", b =>
                {
                    b.Property<int>("GuestEntryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GuestEntryID"));

                    b.Property<string>("Bazdid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Companions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Eghamat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gift")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Guests")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HadafBazdid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jalasat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Khodro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lunch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MahalPazirayi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasolAnjam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasolPeygiry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MohlatAnjam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MojavezKhodro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_Sazman")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Noe_Mosaferat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Req_Section")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Req_UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S_persiandate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaatKhoroj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaateVorud")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SharhMavared")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TarikhVorud_persiandate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("TayidModirVahed")
                        .HasColumnType("bit");

                    b.Property<string>("Time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TozihatModirVahed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tozihat_Darkhast")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tozihat_DarkhastKonnande")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tozihat_Edary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tozihat_ModirAmel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tozihat_Negahbani")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vorud_Saat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vorud_persiandate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GuestEntryID");

                    b.ToTable("GuestEntries");
                });

            modelBuilder.Entity("ERP.Models.Meeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Absentees")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Attendees")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeetingNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecretaryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tarikh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SecretaryId");

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("ERP.Models.MeetingAccept", b =>
                {
                    b.Property<int>("MeetingAcceptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MeetingAcceptID"));

                    b.Property<string>("AcknowledgedAt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MeetingId")
                        .HasColumnType("int");

                    b.Property<bool>("Seen")
                        .HasColumnType("bit");

                    b.Property<string>("UserInMeetingID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MeetingAcceptID");

                    b.HasIndex("MeetingId");

                    b.ToTable("MeetingAccepts");
                });

            modelBuilder.Entity("ERP.Models.MeetingDecision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Datefollowup1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Datefollowup2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Deadline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FollowUpPersonId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MeetingId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsiblePersonId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resultfollowup1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resultfollowup2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId");

                    b.ToTable("MeetingDecisions");
                });

            modelBuilder.Entity("ERP.Models.MissionReport", b =>
                {
                    b.Property<int>("MissionReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MissionReportID"));

                    b.Property<string>("AzTaraf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Desclocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DispatchedPersonnel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DropdownVar001")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DropdownVar002")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DropdownVar003")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("End_Hour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("End_Hour2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("End_persiandate_var")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("End_persiandate_var3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Janeshin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mamuriat_Sazman")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerUserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetPersonnel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MissionExpenses")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modat_mamuriat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Noe_Mamuriat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number_Hokm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number_Personeli")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Radio_Tayid1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Radio_Tayid2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rahgiri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Req_UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Req_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S_persiandate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shahr_Mamuriat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sharh_Mamuriat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Start_Hour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Start_Hour2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Start_persiandate_var")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Start_persiandate_var2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TozihatGozaresh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TozihatKargozini")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TozihatSarparastedari")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tozihat_Tayid1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tozihat_Tayid2")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MissionReportID");

                    b.ToTable("MissionReports");
                });

            modelBuilder.Entity("ERP.Models.OutsourcingItem", b =>
                {
                    b.Property<int>("OutsourcingItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OutsourcingItemID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OutsourcingProductionID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OutsourcingItemID");

                    b.HasIndex("OutsourcingProductionID");

                    b.ToTable("OutsourcingItems");
                });

            modelBuilder.Entity("ERP.Models.OutsourcingProduction", b =>
                {
                    b.Property<int>("OutsourcingProductionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OutsourcingProductionID"));

                    b.Property<string>("Darkhast_persiandate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Khoruj_persiandate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MahalDaryaft")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_Darkhastkonnande")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S_persiandate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shomare_Serial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TayidMali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TayidMasool")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TayidModirAmel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TayidTadarokat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tayid_Sanaye")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeKhoruj_persiandate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tozihat_Anbar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tozihat_Mali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tozihat_Masool")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tozihat_ModirAmel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tozihat_Negahbani")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tozihat_Net")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tozihat_Tadarokat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tozihat_TayidSanaye")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OutsourcingProductionID");

                    b.ToTable("OutsourcingProductions");
                });

            modelBuilder.Entity("ERP.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<string>("CodeProduct")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupTypeA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupTypeB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMeter")
                        .HasColumnType("bit");

                    b.Property<string>("NameProduct")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameProductMarket")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoeProduct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuantityINBox")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zarib")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ERP.Models.ProductCheck", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateGenerate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Number_Device")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Serial_Product")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Step_Procedure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Serial_Product")
                        .HasDatabaseName("IX_ProductChecks_Serial");

                    b.ToTable("ProductChecks");
                });

            modelBuilder.Entity("ERP.Models.Referral", b =>
                {
                    b.Property<int>("ReferralID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReferralID"));

                    b.Property<DateTime>("CreateON")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FirstView")
                        .HasColumnType("datetime2");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuidGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReferralID");

                    b.ToTable("Referrals");
                });

            modelBuilder.Entity("ERP.Models.Roles", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("ERP.Models.SMT", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("DataValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("smt");
                });

            modelBuilder.Entity("ERP.Models.UserGroup", b =>
                {
                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("GroupID")
                        .HasColumnType("int");

                    b.HasKey("UserID", "GroupID");

                    b.HasIndex("GroupID");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("ERP.Models.Users", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustCodeAmel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("InTFC")
                        .HasColumnType("bit");

                    b.Property<int>("IntId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NationalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Post")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ERP.Models.ViewProcess", b =>
                {
                    b.Property<int>("ViewProcessID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ViewProcessID"));

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsView")
                        .HasColumnType("bit");

                    b.Property<string>("ReceiverID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SendDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SenderID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ViewDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ViewProcessID");

                    b.ToTable("ViewProcesss");
                });

            modelBuilder.Entity("ERP.Models.WorkReport", b =>
                {
                    b.Property<int>("WorkReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkReportID"));

                    b.Property<DateTime>("CreateON")
                        .HasColumnType("datetime2");

                    b.Property<string>("DateWorkReport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FinishTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuidFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Member")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TimeHours")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WorkReportID");

                    b.ToTable("WorkReports");
                });

            modelBuilder.Entity("ERP.Models.WorkflowAccess", b =>
                {
                    b.Property<int>("WorkflowAccessID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkflowAccessID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WorkflowAccessID");

                    b.ToTable("WorkflowAccesses");
                });

            modelBuilder.Entity("ERP.Models.WorkflowInstance", b =>
                {
                    b.Property<int>("WorkflowInstanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkflowInstanceID"));

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignedUserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEditor")
                        .HasColumnType("bit");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkFlowID")
                        .HasColumnType("int");

                    b.HasKey("WorkflowInstanceID");

                    b.ToTable("WorkflowInstances");
                });

            modelBuilder.Entity("ERP.Models.WorkflowSection", b =>
                {
                    b.Property<int>("WorkflowSectionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkflowSectionID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WorkflowSectionID");

                    b.ToTable("WorkflowSections");
                });

            modelBuilder.Entity("ERP.Models.WorkflowStep", b =>
                {
                    b.Property<int>("WorkflowStepID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkflowStepID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NextSteps")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WorkflowStepID");

                    b.ToTable("WorkflowSteps");
                });

            modelBuilder.Entity("ERP.Models.asset.AssestCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("AssestCategories");
                });

            modelBuilder.Entity("ERP.Models.asset.AssestUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssestUserTypes")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("AssestUsers");
                });

            modelBuilder.Entity("ERP.Models.asset.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AssetCode")
                        .IsUnique();

                    b.HasIndex("CategoryId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("ERP.Models.asset.AssetHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssestUserId")
                        .HasColumnType("int");

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<int?>("AssetPropertyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("FromUserId")
                        .HasColumnType("int");

                    b.Property<int>("ToUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssestUserId");

                    b.HasIndex("AssetId");

                    b.HasIndex("AssetPropertyId");

                    b.HasIndex("FromUserId");

                    b.HasIndex("ToUserId");

                    b.ToTable("AssetHistories");
                });

            modelBuilder.Entity("ERP.Models.asset.AssetProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastAssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastOwnerUserId")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PropertyValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("LastOwnerUserId");

                    b.ToTable("AssetProperties");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ERP.Models.ChatMessage", b =>
                {
                    b.HasOne("ERP.Models.Users", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP.Models.Users", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("ERP.Models.GoodsConsignedItemGuard", b =>
                {
                    b.HasOne("ERP.Models.GoodsConsigned", "GoodsConsigned")
                        .WithMany("ReturnedItems")
                        .HasForeignKey("GoodsConsignedID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoodsConsigned");
                });

            modelBuilder.Entity("ERP.Models.Meeting", b =>
                {
                    b.HasOne("ERP.Models.Users", "Secretary")
                        .WithMany()
                        .HasForeignKey("SecretaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Secretary");
                });

            modelBuilder.Entity("ERP.Models.MeetingAccept", b =>
                {
                    b.HasOne("ERP.Models.Meeting", "Meeting")
                        .WithMany("MeetingAccept")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("ERP.Models.MeetingDecision", b =>
                {
                    b.HasOne("ERP.Models.Meeting", "Meeting")
                        .WithMany("MeetingDecisions")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("ERP.Models.OutsourcingItem", b =>
                {
                    b.HasOne("ERP.Models.OutsourcingProduction", null)
                        .WithMany("OutsourcingItems")
                        .HasForeignKey("OutsourcingProductionID");
                });

            modelBuilder.Entity("ERP.Models.UserGroup", b =>
                {
                    b.HasOne("ERP.Models.Group", null)
                        .WithMany("UserGroups")
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ERP.Models.asset.AssestCategory", b =>
                {
                    b.HasOne("ERP.Models.asset.AssestCategory", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ERP.Models.asset.Asset", b =>
                {
                    b.HasOne("ERP.Models.asset.AssestCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ERP.Models.asset.AssetHistory", b =>
                {
                    b.HasOne("ERP.Models.asset.AssestUser", null)
                        .WithMany("AssetHistories")
                        .HasForeignKey("AssestUserId");

                    b.HasOne("ERP.Models.asset.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Models.asset.AssetProperty", "AssetProperty")
                        .WithMany()
                        .HasForeignKey("AssetPropertyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERP.Models.asset.AssestUser", "AssestUser")
                        .WithMany()
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP.Models.asset.AssestUser", "AssestToUser")
                        .WithMany()
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssestToUser");

                    b.Navigation("AssestUser");

                    b.Navigation("Asset");

                    b.Navigation("AssetProperty");
                });

            modelBuilder.Entity("ERP.Models.asset.AssetProperty", b =>
                {
                    b.HasOne("ERP.Models.asset.Asset", "Asset")
                        .WithMany("Properties")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Models.asset.AssestCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP.Models.asset.AssestUser", "LastOwnerUser")
                        .WithMany()
                        .HasForeignKey("LastOwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Asset");

                    b.Navigation("Category");

                    b.Navigation("LastOwnerUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("ERP.Models.Roles", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ERP.Models.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ERP.Models.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("ERP.Models.Roles", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Models.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ERP.Models.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ERP.Models.GoodsConsigned", b =>
                {
                    b.Navigation("ReturnedItems");
                });

            modelBuilder.Entity("ERP.Models.Group", b =>
                {
                    b.Navigation("UserGroups");
                });

            modelBuilder.Entity("ERP.Models.Meeting", b =>
                {
                    b.Navigation("MeetingAccept");

                    b.Navigation("MeetingDecisions");
                });

            modelBuilder.Entity("ERP.Models.OutsourcingProduction", b =>
                {
                    b.Navigation("OutsourcingItems");
                });

            modelBuilder.Entity("ERP.Models.asset.AssestCategory", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("ERP.Models.asset.AssestUser", b =>
                {
                    b.Navigation("AssetHistories");
                });

            modelBuilder.Entity("ERP.Models.asset.Asset", b =>
                {
                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
